# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Release'
  test_catalog: $(db_catalog)_test

stages:
- stage: Build_And_Unit_Test
  variables:
    dacpacLocation: 'src\VideoRSSDb\bin\$(buildConfiguration)\VideoRSSDb.dacpac'
  jobs:
  - job: Database
    variables:
      sqlproj: 'src\VideoRSSDb\VideoRSSDb.sqlproj'
      dbLocation: src
      unitTestName: VideoRSSDb.UnitTests
      unitTestProj: '$(dbLocation)\$(unitTestName)\$(unitTestName).csproj'
      assemblyLocation: $(dbLocation)\$(unitTestName)\bin\$(testConfiguration)
    steps:
    - task: MSBuild@1
      inputs:
        configuration: $(buildConfiguration)
        solution: $(sqlproj)
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: $(azure_subscription)
        authenticationType: aadAuthenticationPassword
        serverName: $(db_source)
        databaseName: $(test_catalog)
        aadSqlUsername: $(db_username)
        aadSqlPassword: $(db_password)
        deployType: DacpacTask
        deploymentAction: Publish
        dacpacFile: $(dacpacLocation)
    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: $(unitTestProj)
        feedsToUse: Select
        includeNuGetOrg: true
        restoreDirectory: '$(Build.SourcesDirectory)\src\packages'
    - task: MSBuild@1
      inputs:
        configuration: $(testConfiguration)
        solution: $(unitTestProj)
        msbuildVersion: 16.0
        clean: true
    - task: VSTest@2
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: '$(unitTestName).dll'
        searchFolder: $(assemblyLocation)
        configuration: $(testConfiguration)
        overrideTestrunParameters: '-override_connection_string true -db_source $(db_source) -db_catalog $(test_catalog) -db_username $(db_username) -db_password $(db_password)'
    - publish:  $(dacpacLocation)
      artifact: VideoRSSDbDacPac
- stage: Deployment
  dependsOn: Build_And_Unit_Test
  jobs:
  - job: DeployDatabase
    steps:
    - download: current
      artifact: VideoRSSDbDacPac
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: $(azure_subscription)
        authenticationType: aadAuthenticationPassword
        serverName: $(db_source)
        databaseName: $(db_catalog)
        aadSqlUsername: $(db_username)
        aadSqlPassword: $(db_password)
        deployType: DacpacTask
        deploymentAction: Publish
        dacpacFile: $(Pipeline.Workspace)\**\*.dacpac
